name: firehub
description: "A hub for firebase's apis"
version: 0.0.2
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  firebase_analytics: ^12.0.0
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^7.0.0